# Generated by Django 4.2.1 on 2023-06-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='imgUrl',
            field=models.ImageField(blank=True, default='blog-8-1000x600.jpg', upload_to='images'),
        ),
    ]
